### ISSUE TITLE
fglrx module failed build with  'KCL_fpu_save_init' defined but not used [-Wunused-function]

### ISSUE THREAD

**Issue by kergalym** [imageguy/fglrx-for-Fedora#12]
Hi
Yes I know this is for Fedora, but I use Gentoo.
I successfully applied fglrx_kernel_4.11.diff against linux-4.11.1-gentoo kernel, but module building fails always.
I also tried to patch the driver manually, but no luck, same thing.
May be I should use this patch against vanilla kernel? 

Build log is attached
[build.txt](https://github.com/imageguy/fglrx-for-Fedora/files/1113646/build.txt)

**Comment by imageguy** [comment]
Hi,
Is this the first time you tried one of the patches here? I see a bunch of fails in the build.txt, starting with problems in firegl_public.h. If this is the first time you tried one of the patches on Gentoo, then it might be due to differences between distros. We normally get our patches from ArchLinux, but I never worked with Gentoo and don't know if it could be different in some crucial piece. You might try posting on discussion page https://bluehatrecord.wordpress.com/2016/03/25/installing-the-proprietary-amd-crimson-driver-on-fedora-23-with-linux-kernel-4-4-6-300/ - someone might know.

**Comment by imageguy** [comment]
I'll close this, since there were no comments for quite a while and the current kernel is at 4.14.
