### ISSUE TITLE
please port it for kernel 5.12 or high ?

### ISSUE THREAD

**Issue by sajjads24** [imageguy/fglrx-for-Fedora#21]
Hi
how make this patch for kernel 5.12 on fedora 34 ?
please port it for kernel 5.12 or high ?

**Comment by imageguy** [comment]
Hi,
I haven't looked at this in a very long while. I poked around a little and the news is not good. I don't have a board that uses fglrx any more, so I can't do any porting, patching or testing myself. Once I no longer had a fglrx running on my own machine, I started relying on the archlinux distro, since they would patch every time something broke and I would roll their patches into the cumulative patch. Unfortunately, they no longer support it, so I don't have a place to get the fixes.

That means that I can't update the patch any more and can't help you. It is quite possible that the kernel has changed enough that fglrx can't be modified to fit any more, but I simply don't know. If you find that someone does have fglrx running on 5.12, I'd certainly be willing to see if we can fold whatever changed into the patch. 

I'll leave this open for a while longer just in case, but the outlook is grim.

**Comment by mirh** [comment]
https://web.archive.org/web/20201101191708/https://aur.archlinux.org/packages/catalyst-test/
You can get up to 5.3 with relative ease, but after that nobody really bothered (I think maybe some nvidia 304/340 patch could be repurposed, but idk). 

And to a reason too, imho. Put aside the obvious time/obsolescence, FOSS opencl is seeing the [light](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7241) at the end of the tunnel of uselessness. 
And opengl has finally broken the barrier of soft-fp64 with NIR (that landed in mesa 21.0).
Not that either of them is really workable atm, but the effort involved now is low enough that you could just as well focus on that. And same story even with the rare odd balls with power management or framebuffer dividers (not really much kernel people left caring for radeon, but I would also be pissed off if people never followed up bug reports)

**Comment by imageguy** [comment]
Thanks! I took a look at my stuff and this has two patches I'm missing. I'll happily roll them into the cumulative patch. Beyond that, I don't really plan to do anything else unless some other patch shows up that I can pick up.

**Comment by imageguy** [comment]
I've made the patch that contains both 5.0 and 5.1 patches. As always, beware, since I can't test the patches I make.

**Comment by mirh** [comment]
You should check [my tree](https://github.com/mirh/packages-legacy/tree/master/catalyst/linux53-extramodules) for more
I had 5.3 working, plus a nice patch from [gentoo](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=6913a35966d89d28ed6208ab9a58c20fd8a80396) that fixes a preempt warning.

**Comment by imageguy** [comment]
Thank you so much! I've added  them both to the cumulative patch. It would be fantastic if you could drop me a note if you get or make any more patches. I might forget to check your tree, as I've forgotten to check the archlinux tree in a long while.

**Comment by mirh** [comment]
I'm not on AMD (or well, linux) anymore so no can do.
